@host = http://localhost:8080

### Basic workflow call
POST {{host}}/api/workflows
Content-Type: application/json

{
  "prompt": "Workflow to extract issue ids from attached pdf"
}


### Change workflow
POST {{host}}/api/workflows
Content-Type: application/json

{
  "prompt": "Lets include issues that only has PROJECT in their title if mentioned along the ticket number in pdf",
  "workflow": ""
}

### Basic workflow call remote
POST https://hktn2025-22-ai-workflow.fly.dev/api/workflows
Content-Type: application/json

{
  "prompt": "Workflow to extract issue ids from attached pdf"
}