
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          #model: gpt-4o-mini
          temperature: 1
          model: gpt-5-mini
  main:
    banner-mode: off
server:
  tomcat:
    connection-timeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: health,info
      cors:
        allowed-origins: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true